const races = {
  Throughbred: [
    {
      VenueId: 523,
      Venue: 'Fontwell Park',
      Race1: {
        EventTypeId: 1,
        MasterEventId: 0,
        EventId: 10214386,
        VenueId: 0,
        Venue: null,
        CountryCode: null,
        RaceNumber: 3,
        AdvertisedStartTime: '/Date(1653795540000)/',
        ResultStatusId: 0,
        SecondsToJump: 65,
        HasFixedMarkets: false,
        IsOpenForBetting: false,
        MarketShortcuts: null,
        Results: null,
        MasterCategoryName: null,
        EventName: null,
      },
      CountryCode: 'GBR',
      MasterCategoryName: 'Overseas-Racing',
    },
    {
      VenueId: 470,
      Venue: 'Longchamp',
      Race1: {
        EventTypeId: 1,
        MasterEventId: 0,
        EventId: 10226173,
        VenueId: 0,
        Venue: null,
        CountryCode: null,
        RaceNumber: 4,
        AdvertisedStartTime: '/Date(1653795900000)/',
        ResultStatusId: 0,
        SecondsToJump: 425,
        HasFixedMarkets: false,
        IsOpenForBetting: false,
        MarketShortcuts: null,
        Results: null,
        MasterCategoryName: null,
        EventName: null,
      },
      CountryCode: 'FRA',
      MasterCategoryName: 'Overseas-Racing',
    },
    {
      VenueId: 493,
      Venue: 'Kelso',
      Race1: {
        EventTypeId: 1,
        MasterEventId: 0,
        EventId: 10214398,
        VenueId: 0,
        Venue: null,
        CountryCode: null,
        RaceNumber: 2,
        AdvertisedStartTime: '/Date(1653796020000)/',
        ResultStatusId: 0,
        SecondsToJump: 545,
        HasFixedMarkets: false,
        IsOpenForBetting: false,
        MarketShortcuts: null,
        Results: null,
        MasterCategoryName: null,
        EventName: null,
      },
      CountryCode: 'GBR',
      MasterCategoryName: 'Overseas-Racing',
    },
    {
      VenueId: 693,
      Venue: 'Turffontein',
      Race1: {
        EventTypeId: 1,
        MasterEventId: 0,
        EventId: 10069281,
        VenueId: 0,
        Venue: null,
        CountryCode: null,
        RaceNumber: 7,
        AdvertisedStartTime: '/Date(1653796260000)/',
        ResultStatusId: 0,
        SecondsToJump: 785,
        HasFixedMarkets: false,
        IsOpenForBetting: false,
        MarketShortcuts: null,
        Results: null,
        MasterCategoryName: null,
        EventName: null,
      },
      CountryCode: 'ZAF',
      MasterCategoryName: 'Overseas-Racing',
    },
    {
      VenueId: 537,
      Venue: 'Uttoxeter',
      Race1: {
        EventTypeId: 1,
        MasterEventId: 0,
        EventId: 10215166,
        VenueId: 0,
        Venue: null,
        CountryCode: null,
        RaceNumber: 3,
        AdvertisedStartTime: '/Date(1653796560000)/',
        ResultStatusId: 0,
        SecondsToJump: 1085,
        HasFixedMarkets: false,
        IsOpenForBetting: false,
        MarketShortcuts: null,
        Results: null,
        MasterCategoryName: null,
        EventName: null,
      },
      CountryCode: 'GBR',
      MasterCategoryName: 'Overseas-Racing',
    },
    {
      VenueId: 555,
      Venue: 'Punchestown',
      Race1: {
        EventTypeId: 1,
        MasterEventId: 0,
        EventId: 10215325,
        VenueId: 0,
        Venue: null,
        CountryCode: null,
        RaceNumber: 3,
        AdvertisedStartTime: '/Date(1653797100000)/',
        ResultStatusId: 0,
        SecondsToJump: 1625,
        HasFixedMarkets: false,
        IsOpenForBetting: false,
        MarketShortcuts: null,
        Results: null,
        MasterCategoryName: null,
        EventName: null,
      },
      CountryCode: 'IRL',
      MasterCategoryName: 'Overseas-Racing',
    },
    {
      VenueId: 679,
      Venue: 'Pimlico',
      Race1: {
        EventTypeId: 1,
        MasterEventId: 0,
        EventId: 10227026,
        VenueId: 0,
        Venue: null,
        CountryCode: null,
        RaceNumber: 1,
        AdvertisedStartTime: '/Date(1653806400000)/',
        ResultStatusId: 0,
        SecondsToJump: 10925,
        HasFixedMarkets: false,
        IsOpenForBetting: false,
        MarketShortcuts: null,
        Results: null,
        MasterCategoryName: null,
        EventName: null,
      },
      CountryCode: 'USA',
      MasterCategoryName: 'Overseas-Racing',
    },
    {
      VenueId: 675,
      Venue: 'Gulfstream Park',
      Race1: {
        EventTypeId: 1,
        MasterEventId: 0,
        EventId: 10227042,
        VenueId: 0,
        Venue: null,
        CountryCode: null,
        RaceNumber: 1,
        AdvertisedStartTime: '/Date(1653807900000)/',
        ResultStatusId: 0,
        SecondsToJump: 12425,
        HasFixedMarkets: false,
        IsOpenForBetting: false,
        MarketShortcuts: null,
        Results: null,
        MasterCategoryName: null,
        EventName: null,
      },
      CountryCode: 'USA',
      MasterCategoryName: 'Overseas-Racing',
    },
    {
      VenueId: 674,
      Venue: 'Santa Anita Park',
      Race1: {
        EventTypeId: 1,
        MasterEventId: 0,
        EventId: 10227062,
        VenueId: 0,
        Venue: null,
        CountryCode: null,
        RaceNumber: 1,
        AdvertisedStartTime: '/Date(1653818400000)/',
        ResultStatusId: 0,
        SecondsToJump: 22925,
        HasFixedMarkets: false,
        IsOpenForBetting: false,
        MarketShortcuts: null,
        Results: null,
        MasterCategoryName: null,
        EventName: null,
      },
      CountryCode: 'USA',
      MasterCategoryName: 'Overseas-Racing',
    },
    {
      VenueId: 673,
      Venue: 'Golden Gate',
      Race1: {
        EventTypeId: 1,
        MasterEventId: 0,
        EventId: 10227068,
        VenueId: 0,
        Venue: null,
        CountryCode: null,
        RaceNumber: 1,
        AdvertisedStartTime: '/Date(1653819300000)/',
        ResultStatusId: 0,
        SecondsToJump: 23825,
        HasFixedMarkets: false,
        IsOpenForBetting: false,
        MarketShortcuts: null,
        Results: null,
        MasterCategoryName: null,
        EventName: null,
      },
      CountryCode: 'USA',
      MasterCategoryName: 'Overseas-Racing',
    },
    {
      VenueId: 1102,
      Venue: 'Prairie Meadows',
      Race1: {
        EventTypeId: 1,
        MasterEventId: 0,
        EventId: 10227076,
        VenueId: 0,
        Venue: null,
        CountryCode: null,
        RaceNumber: 1,
        AdvertisedStartTime: '/Date(1653822000000)/',
        ResultStatusId: 0,
        SecondsToJump: 26525,
        HasFixedMarkets: false,
        IsOpenForBetting: false,
        MarketShortcuts: null,
        Results: null,
        MasterCategoryName: null,
        EventName: null,
      },
      CountryCode: 'USA',
      MasterCategoryName: 'Overseas-Racing',
    },
  ],
  Harness: [
    {
      VenueId: 879,
      Venue: 'Reims',
      Race1: {
        EventTypeId: 2,
        MasterEventId: 0,
        EventId: 10226185,
        VenueId: 0,
        Venue: null,
        CountryCode: null,
        RaceNumber: 1,
        AdvertisedStartTime: '/Date(1653799320000)/',
        ResultStatusId: 0,
        SecondsToJump: 3845,
        HasFixedMarkets: false,
        IsOpenForBetting: false,
        MarketShortcuts: null,
        Results: null,
        MasterCategoryName: null,
        EventName: null,
      },
      CountryCode: 'FRA',
      MasterCategoryName: 'Overseas-Trots',
    },
  ],
  Greyhound: [
    {
      VenueId: 15841,
      Venue: 'Towcester',
      Race1: {
        EventTypeId: 3,
        MasterEventId: 0,
        EventId: 10252964,
        VenueId: 0,
        Venue: null,
        CountryCode: null,
        RaceNumber: 4,
        AdvertisedStartTime: '/Date(1653796320000)/',
        ResultStatusId: 0,
        SecondsToJump: 845,
        HasFixedMarkets: false,
        IsOpenForBetting: false,
        MarketShortcuts: null,
        Results: null,
        MasterCategoryName: null,
        EventName: null,
      },
      CountryCode: 'GBR',
      MasterCategoryName: 'Overseas-Greyhound',
    },
    {
      VenueId: 15894,
      Venue: 'Kinsley',
      Race1: {
        EventTypeId: 3,
        MasterEventId: 0,
        EventId: 10252997,
        VenueId: 0,
        Venue: null,
        CountryCode: null,
        RaceNumber: 4,
        AdvertisedStartTime: '/Date(1653796440000)/',
        ResultStatusId: 0,
        SecondsToJump: 965,
        HasFixedMarkets: false,
        IsOpenForBetting: false,
        MarketShortcuts: null,
        Results: null,
        MasterCategoryName: null,
        EventName: null,
      },
      CountryCode: 'GBR',
      MasterCategoryName: 'Overseas-Greyhound',
    },
    {
      VenueId: 15832,
      Venue: 'Central Park',
      Race1: {
        EventTypeId: 3,
        MasterEventId: 0,
        EventId: 10253033,
        VenueId: 0,
        Venue: null,
        CountryCode: null,
        RaceNumber: 1,
        AdvertisedStartTime: '/Date(1653808140000)/',
        ResultStatusId: 0,
        SecondsToJump: 12665,
        HasFixedMarkets: false,
        IsOpenForBetting: false,
        MarketShortcuts: null,
        Results: null,
        MasterCategoryName: null,
        EventName: null,
      },
      CountryCode: 'GBR',
      MasterCategoryName: 'Overseas-Greyhound',
    },
    {
      VenueId: 13043,
      Venue: 'Henlow',
      Race1: {
        EventTypeId: 3,
        MasterEventId: 0,
        EventId: 10253060,
        VenueId: 0,
        Venue: null,
        CountryCode: null,
        RaceNumber: 1,
        AdvertisedStartTime: '/Date(1653808620000)/',
        ResultStatusId: 0,
        SecondsToJump: 13145,
        HasFixedMarkets: false,
        IsOpenForBetting: false,
        MarketShortcuts: null,
        Results: null,
        MasterCategoryName: null,
        EventName: null,
      },
      CountryCode: 'GBR',
      MasterCategoryName: 'Overseas-Greyhound',
    },
    {
      VenueId: 12973,
      Venue: 'Swindon Bags',
      Race1: {
        EventTypeId: 3,
        MasterEventId: 0,
        EventId: 10253089,
        VenueId: 0,
        Venue: null,
        CountryCode: null,
        RaceNumber: 1,
        AdvertisedStartTime: '/Date(1653808740000)/',
        ResultStatusId: 0,
        SecondsToJump: 13265,
        HasFixedMarkets: false,
        IsOpenForBetting: false,
        MarketShortcuts: null,
        Results: null,
        MasterCategoryName: null,
        EventName: null,
      },
      CountryCode: 'GBR',
      MasterCategoryName: 'Overseas-Greyhound',
    },
  ],
}

export default races
